### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by candrews** [ehloonion/onionrouter#19]
* onionrouter version: 0.5.2
* Python version: 3.8
* Operating System: Linux

### Description
onionrouter doesn't work and displays this stack trace:
```
$ onionrouter -d
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/onionrouter/msockets.py", line 23, in resolve
    result = rerouter.run(addr)
  File "/usr/lib/python3.8/site-packages/onionrouter/rerouter.py", line 64, in run
    domain = self.get_domain(address)
  File "/usr/lib/python3.8/site-packages/onionrouter/rerouter.py", line 48, in get_domain
    split_addr = address.split("@")
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/onionrouter/msockets.py", line 30, in resolve
    conn.sendall("500 {0}".format(err))
TypeError: a bytes-like object is required, not 'str'
```
### What I Did

```
onionrouter -d
```

**Comment by ioparaskev** [comment]
Yeap this seems to be a python 3 issue
